#!/usr/bin/env python3
"""
evaluate_toy_recovery.py

Evaluate the pedagogical toy dataset generated by simulate_toy_fusion_data.py
after fitting with shared_spatial_model.py.

Outputs
-------
- <prefix>_summary.json
- <prefix>_per_factor_metrics.csv

Reported checks
---------------
1. recovery of the generating spatial subspace;
2. signed-permutation alignment of spatial factors;
3. EEG and fMRI strength recovery after alignment;
4. clean EEG covariance recovery on the observed EEG support and over the
   full retained LB space;
5. clean fMRI covariance recovery.

Subspace recovery is invariant to signed permutation. Because factor signs do
not affect Phi diag(lambda) Phi^T, only Phi is sign aligned; nonnegative
strengths are permuted but not sign changed.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path

import numpy as np
import pandas as pd
import scipy.linalg as la
from scipy.optimize import linear_sum_assignment


def ensure_dir(path: Path) -> None:
    path.mkdir(parents=True, exist_ok=True)


def sigma_from_phi_lambda(Phi: np.ndarray, lam: np.ndarray) -> np.ndarray:
    return (Phi * lam[None, :]) @ Phi.T


def rel_frob(A: np.ndarray, B: np.ndarray, W: np.ndarray | None = None) -> float:
    if W is not None:
        A = W * A
        B = W * B
    denom = float(la.norm(np.asarray(A).ravel()))
    if denom <= 1e-12:
        return float("nan")
    return float(la.norm((np.asarray(A) - np.asarray(B)).ravel()) / denom)


def corr_safe(x: np.ndarray, y: np.ndarray) -> float:
    x = np.asarray(x).ravel()
    y = np.asarray(y).ravel()
    if float(np.std(x)) <= 1e-12 or float(np.std(y)) <= 1e-12:
        return float("nan")
    return float(np.corrcoef(x, y)[0, 1])


def reconstruct_eeg(Phi: np.ndarray, lam: np.ndarray) -> np.ndarray:
    n, F, _ = lam.shape
    K = Phi.shape[0]
    out = np.zeros((n, F, K, K), dtype=np.float32)
    for i in range(n):
        for f in range(F):
            out[i, f] = sigma_from_phi_lambda(Phi, lam[i, f])
    return out


def reconstruct_fmri(Phi: np.ndarray, lam: np.ndarray) -> np.ndarray:
    n, _ = lam.shape
    K = Phi.shape[0]
    out = np.zeros((n, K, K), dtype=np.float32)
    for i in range(n):
        out[i] = sigma_from_phi_lambda(Phi, lam[i])
    return out


def main() -> None:
    ap = argparse.ArgumentParser(description="Evaluate toy shared-spatial-factor recovery.")
    ap.add_argument("--data", default="toy_fusion_data.npz")
    ap.add_argument("--fit", default="toy_fit.npz")
    ap.add_argument("--outdir", default="toy_recovery")
    ap.add_argument("--prefix", default="toy_recovery")
    args = ap.parse_args()

    outdir = Path(args.outdir).expanduser().resolve()
    ensure_dir(outdir)

    toy = np.load(args.data, allow_pickle=True)
    fit = np.load(args.fit, allow_pickle=True)

    Phi_true = np.asarray(toy["Phi_true"], float)
    Phi_hat = np.asarray(fit["Phi_hat"], float)
    lam_eeg_true = np.asarray(toy["lambda_eeg_true"], float)
    lam_eeg_hat = np.asarray(fit["lambda_hat"], float)

    if "lambda_fmri_true" not in toy or "lambda_fmri_hat" not in fit:
        raise KeyError(
            "Toy evaluation requires separate fMRI strengths. "
            "Fit with --fmri_mode separate."
        )
    lam_fmri_true = np.asarray(toy["lambda_fmri_true"], float)
    lam_fmri_hat = np.asarray(fit["lambda_fmri_hat"], float)

    K, R_true = Phi_true.shape
    K_hat, R_hat = Phi_hat.shape
    if K != K_hat:
        raise ValueError(f"K mismatch: truth={K}, fit={K_hat}")
    if R_true != R_hat:
        raise ValueError(
            "This pedagogical evaluator assumes fitted rank equals generating rank: "
            f"R_true={R_true}, R_hat={R_hat}"
        )

    # Subspace recovery.
    M = Phi_true.T @ Phi_hat
    svals = np.clip(la.svdvals(M), 0.0, 1.0)
    angles_deg = np.degrees(np.arccos(svals))
    P_true = Phi_true @ Phi_true.T
    P_hat = Phi_hat @ Phi_hat.T
    projection_error = rel_frob(P_true, P_hat)

    # Match fitted columns to truth by maximum absolute inner product.
    row_ind, col_ind = linear_sum_assignment(-np.abs(M))
    order = np.argsort(row_ind)
    row_ind = row_ind[order]
    perm = col_ind[order]

    Phi_aligned = Phi_hat[:, perm]
    lam_eeg_aligned = lam_eeg_hat[:, :, perm]
    lam_fmri_aligned = lam_fmri_hat[:, perm]

    signs = np.sign(np.sum(Phi_true[:, row_ind] * Phi_aligned, axis=0))
    signs[signs == 0] = 1.0
    Phi_aligned = Phi_aligned * signs[None, :]

    Phi_truth_ordered = Phi_true[:, row_ind]
    lam_eeg_truth_ordered = lam_eeg_true[:, :, row_ind]
    lam_fmri_truth_ordered = lam_fmri_true[:, row_ind]

    phi_inner = np.sum(Phi_truth_ordered * Phi_aligned, axis=0)
    phi_l2 = np.sqrt(np.sum((Phi_truth_ordered - Phi_aligned) ** 2, axis=0))

    eeg_lambda_rel = rel_frob(lam_eeg_truth_ordered, lam_eeg_aligned)
    fmri_lambda_rel = rel_frob(lam_fmri_truth_ordered, lam_fmri_aligned)

    # Reconstruct clean model-implied connectivity.
    C_eeg_hat = reconstruct_eeg(Phi_hat, lam_eeg_hat)
    C_fmri_hat = reconstruct_fmri(Phi_hat, lam_fmri_hat)

    if "C_eeg_clean" in toy:
        C_eeg_true = np.asarray(toy["C_eeg_clean"], float)
    else:
        C_eeg_true = reconstruct_eeg(Phi_true, lam_eeg_true)

    if "C_fmri_clean" in toy:
        C_fmri_true = np.asarray(toy["C_fmri_clean"], float)
    else:
        C_fmri_true = reconstruct_fmri(Phi_true, lam_fmri_true)

    W_eeg = np.asarray(toy["W_eeg"], float)
    W_fmri = np.asarray(toy["W_fmri"], float)

    eeg_cov_observed_rel = rel_frob(C_eeg_true, C_eeg_hat, W_eeg)
    eeg_cov_full_rel = rel_frob(C_eeg_true, C_eeg_hat)
    fmri_cov_rel = rel_frob(C_fmri_true, C_fmri_hat, W_fmri)

    rows = []
    for j, (r_true, r_hat) in enumerate(zip(row_ind, perm)):
        eeg_true = lam_eeg_true[:, :, r_true]
        eeg_hat = lam_eeg_hat[:, :, r_hat]
        fmri_true = lam_fmri_true[:, r_true]
        fmri_hat = lam_fmri_hat[:, r_hat]

        rows.append(
            {
                "true_factor": int(r_true + 1),
                "matched_hat_factor": int(r_hat + 1),
                "phi_inner_product": float(phi_inner[j]),
                "phi_l2_error": float(phi_l2[j]),
                "eeg_lambda_corr": corr_safe(eeg_true, eeg_hat),
                "eeg_lambda_mae": float(np.mean(np.abs(eeg_true - eeg_hat))),
                "eeg_lambda_rmse": float(np.sqrt(np.mean((eeg_true - eeg_hat) ** 2))),
                "fmri_lambda_corr": corr_safe(fmri_true, fmri_hat),
                "fmri_lambda_mae": float(np.mean(np.abs(fmri_true - fmri_hat))),
                "fmri_lambda_rmse": float(np.sqrt(np.mean((fmri_true - fmri_hat) ** 2))),
            }
        )

    summary = {
        "K": int(K),
        "R_true": int(R_true),
        "R_hat": int(R_hat),
        "subspace_singular_values": [float(x) for x in svals],
        "principal_angles_deg": [float(x) for x in angles_deg],
        "max_principal_angle_deg": float(np.max(angles_deg)),
        "mean_principal_angle_deg": float(np.mean(angles_deg)),
        "projection_matrix_relative_error": float(projection_error),
        "matched_hat_factors_1based": [int(x + 1) for x in perm],
        "phi_inner_products_after_sign_alignment": [float(x) for x in phi_inner],
        "eeg_lambda_relative_frobenius_error": float(eeg_lambda_rel),
        "fmri_lambda_relative_frobenius_error": float(fmri_lambda_rel),
        "eeg_clean_covariance_observed_support_relative_error": float(eeg_cov_observed_rel),
        "eeg_clean_covariance_full_relative_error": float(eeg_cov_full_rel),
        "fmri_clean_covariance_relative_error": float(fmri_cov_rel),
    }

    summary_path = outdir / f"{args.prefix}_summary.json"
    factor_path = outdir / f"{args.prefix}_per_factor_metrics.csv"
    summary_path.write_text(json.dumps(summary, indent=2))
    pd.DataFrame(rows).to_csv(factor_path, index=False)

    print(f"Wrote {summary_path}")
    print(f"Wrote {factor_path}")
    print()
    print("=== Toy recovery summary ===")
    print("Principal angles (deg):", np.round(angles_deg, 3))
    print("Max principal angle (deg):", round(float(np.max(angles_deg)), 3))
    print("Projection-matrix relative error:", round(projection_error, 6))
    print("Mean matched spatial-factor inner product:", round(float(np.mean(phi_inner)), 6))
    print("EEG lambda relative error:", round(eeg_lambda_rel, 6))
    print("fMRI lambda relative error:", round(fmri_lambda_rel, 6))
    print("EEG clean covariance error (observed support):", round(eeg_cov_observed_rel, 6))
    print("EEG clean covariance error (full LB space):", round(eeg_cov_full_rel, 6))
    print("fMRI clean covariance error:", round(fmri_cov_rel, 6))


if __name__ == "__main__":
    main()
