#!/usr/bin/env python3
"""
evaluate_toy_recovery.py

Evaluate recovery on a toy synthetic dataset generated by simulate_toy_fusion_data.py
and fitted by fit_map_fixedR_cov_fast.py.

Outputs:
  - summary.json
  - per_factor_metrics.csv

Main checks:
  1) subspace recovery of Phi (invariant to signed permutation)
  2) signed-permutation matching of columns
  3) EEG/fMRI lambda recovery after alignment
  4) reconstructed clean covariance recovery
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path

import numpy as np
import pandas as pd
import scipy.linalg as la
from scipy.optimize import linear_sum_assignment


def ensure_dir(p: Path) -> None:
    p.mkdir(parents=True, exist_ok=True)


def sigma_from_phi_lambda(Phi: np.ndarray, lam: np.ndarray) -> np.ndarray:
    return (Phi * lam[None, :]) @ Phi.T


def rel_frob(A: np.ndarray, B: np.ndarray) -> float:
    return float(la.norm(A - B) / max(la.norm(A), 1e-12))


def corr_safe(x: np.ndarray, y: np.ndarray) -> float:
    x = np.asarray(x).ravel()
    y = np.asarray(y).ravel()
    sx = np.std(x)
    sy = np.std(y)
    if sx <= 1e-12 or sy <= 1e-12:
        return np.nan
    return float(np.corrcoef(x, y)[0, 1])


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--data", required=True, help="toy_fusion_data.npz")
    ap.add_argument("--fit", required=True, help="toy_fit.npz")
    ap.add_argument("--outdir", required=True)
    ap.add_argument("--prefix", default="toy_recovery")
    args = ap.parse_args()

    outdir = Path(args.outdir).expanduser().resolve()
    ensure_dir(outdir)

    toy = np.load(args.data, allow_pickle=True)
    fit = np.load(args.fit, allow_pickle=True)

    Phi_true = np.asarray(toy["Phi_true"], float)           # (K,R)
    Phi_hat  = np.asarray(fit["Phi_hat"], float)            # (K,Rhat)

    lam_eeg_true = np.asarray(toy["lambda_eeg_true"], float)   # (n,F,R)
    lam_eeg_hat  = np.asarray(fit["lambda_hat"], float)        # (n,F,Rhat)

    has_fmri_true = "lambda_fmri_true" in toy
    has_fmri_hat = "lambda_fmri_hat" in fit

    lam_fmri_true = np.asarray(toy["lambda_fmri_true"], float) if has_fmri_true else None
    lam_fmri_hat  = np.asarray(fit["lambda_fmri_hat"], float) if has_fmri_hat else None

    K, R_true = Phi_true.shape
    K2, R_hat = Phi_hat.shape
    if K != K2:
        raise ValueError(f"Phi_true and Phi_hat have different K: {K} vs {K2}")
    if R_true != R_hat:
        raise ValueError(
            f"This script expects equal working rank and true rank for direct matching: "
            f"R_true={R_true}, R_hat={R_hat}"
        )

    # 1) Subspace recovery (invariant to permutation/sign)
    M = Phi_true.T @ Phi_hat
    svals = la.svdvals(M)
    angles_deg = np.degrees(np.arccos(np.clip(svals, -1.0, 1.0)))

    P_true = Phi_true @ Phi_true.T
    P_hat  = Phi_hat @ Phi_hat.T
    proj_err = rel_frob(P_true, P_hat)

    # 2) Signed-permutation alignment of columns
    cost = -np.abs(M)
    row_ind, col_ind = linear_sum_assignment(cost)

    # reorder estimated columns to match truth order
    perm = col_ind[np.argsort(row_ind)]
    Phi_hat_aligned = Phi_hat[:, perm]
    lam_eeg_hat_aligned = lam_eeg_hat[:, :, perm]
    lam_fmri_hat_aligned = lam_fmri_hat[:, perm] if lam_fmri_hat is not None else None

    # sign-fix columns for display / comparison
    signs = np.sign(np.sum(Phi_true * Phi_hat_aligned, axis=0))
    signs[signs == 0] = 1.0
    Phi_hat_aligned = Phi_hat_aligned * signs[None, :]
    # lambdas stay unchanged (model is sign-invariant through Phi Phi^T)

    phi_col_inner = np.sum(Phi_true * Phi_hat_aligned, axis=0)
    phi_col_l2err = np.sqrt(np.sum((Phi_true - Phi_hat_aligned) ** 2, axis=0))

    # 3) Lambda recovery after alignment
    eeg_rel = rel_frob(lam_eeg_true, lam_eeg_hat_aligned)
    corr_eeg = []
    mae_eeg = []
    rmse_eeg = []

    for r in range(R_true):
        corr_eeg.append(corr_safe(lam_eeg_true[:, :, r], lam_eeg_hat_aligned[:, :, r]))
        diff = lam_eeg_true[:, :, r] - lam_eeg_hat_aligned[:, :, r]
        mae_eeg.append(float(np.mean(np.abs(diff))))
        rmse_eeg.append(float(np.sqrt(np.mean(diff ** 2))))

    fmri_rel = None
    corr_fmri = None
    mae_fmri = None
    rmse_fmri = None
    if lam_fmri_true is not None and lam_fmri_hat_aligned is not None:
        fmri_rel = rel_frob(lam_fmri_true, lam_fmri_hat_aligned)
        corr_fmri = []
        mae_fmri = []
        rmse_fmri = []
        for r in range(R_true):
            corr_fmri.append(corr_safe(lam_fmri_true[:, r], lam_fmri_hat_aligned[:, r]))
            diff = lam_fmri_true[:, r] - lam_fmri_hat_aligned[:, r]
            mae_fmri.append(float(np.mean(np.abs(diff))))
            rmse_fmri.append(float(np.sqrt(np.mean(diff ** 2))))

    # 4) Reconstructed clean covariance recovery
    n, F, R = lam_eeg_true.shape
    C_eeg_true = np.zeros((n, F, K, K))
    C_eeg_hat  = np.zeros_like(C_eeg_true)

    for i in range(n):
        for f in range(F):
            C_eeg_true[i, f] = sigma_from_phi_lambda(Phi_true, lam_eeg_true[i, f])
            C_eeg_hat[i, f]  = sigma_from_phi_lambda(Phi_hat_aligned, lam_eeg_hat_aligned[i, f])

    cov_eeg_rel = rel_frob(C_eeg_true, C_eeg_hat)

    cov_fmri_rel = None
    if lam_fmri_true is not None and lam_fmri_hat_aligned is not None:
        C_f_true = np.zeros((n, K, K))
        C_f_hat  = np.zeros_like(C_f_true)
        for i in range(n):
            C_f_true[i] = sigma_from_phi_lambda(Phi_true, lam_fmri_true[i])
            C_f_hat[i]  = sigma_from_phi_lambda(Phi_hat_aligned, lam_fmri_hat_aligned[i])
        cov_fmri_rel = rel_frob(C_f_true, C_f_hat)

    # --------------------------------------------------
    # Save outputs
    summary = {
        "K": int(K),
        "R_true": int(R_true),
        "R_hat": int(R_hat),
        "subspace_singular_values": [float(x) for x in svals],
        "principal_angles_deg": [float(x) for x in angles_deg],
        "projection_matrix_relative_error": float(proj_err),
        "matched_permutation_true_to_hat": [int(x) for x in perm],
        "column_signs_after_alignment": [float(x) for x in signs],
        "phi_column_inner_products": [float(x) for x in phi_col_inner],
        "phi_column_l2_errors": [float(x) for x in phi_col_l2err],
        "eeg_lambda_relative_frobenius_error": float(eeg_rel),
        "eeg_covariance_relative_frobenius_error": float(cov_eeg_rel),
    }

    if fmri_rel is not None:
        summary["fmri_lambda_relative_frobenius_error"] = float(fmri_rel)
    if cov_fmri_rel is not None:
        summary["fmri_covariance_relative_frobenius_error"] = float(cov_fmri_rel)

    summary_path = outdir / f"{args.prefix}_summary.json"
    with open(summary_path, "w") as f:
        json.dump(summary, f, indent=2)

    rows = []
    for r in range(R_true):
        row = {
            "r": r + 1,
            "matched_hat_col": int(perm[r] + 1),
            "sign": float(signs[r]),
            "phi_inner_product": float(phi_col_inner[r]),
            "phi_l2_error": float(phi_col_l2err[r]),
            "eeg_lambda_corr": float(corr_eeg[r]),
            "eeg_lambda_mae": float(mae_eeg[r]),
            "eeg_lambda_rmse": float(rmse_eeg[r]),
        }
        if corr_fmri is not None:
            row["fmri_lambda_corr"] = float(corr_fmri[r])
            row["fmri_lambda_mae"] = float(mae_fmri[r])
            row["fmri_lambda_rmse"] = float(rmse_fmri[r])
        rows.append(row)

    per_factor = pd.DataFrame(rows)
    per_factor_path = outdir / f"{args.prefix}_per_factor_metrics.csv"
    per_factor.to_csv(per_factor_path, index=False)


    print("Wrote:", summary_path)
    print("Wrote:", per_factor_path)
    print()
    print("=== Toy recovery summary ===")
    print("Projection-matrix relative error:", round(float(proj_err), 6))
    print("Principal angles (deg):", np.round(angles_deg, 3))
    print("Matched permutation (true -> estimated):", [int(x + 1) for x in perm])
    print("Phi inner products after alignment:", np.round(phi_col_inner, 4))
    print("EEG lambda relative error:", round(float(eeg_rel), 6))
    print("EEG covariance relative error:", round(float(cov_eeg_rel), 6))
    if fmri_rel is not None:
        print("fMRI lambda relative error:", round(float(fmri_rel), 6))
    if cov_fmri_rel is not None:
        print("fMRI covariance relative error:", round(float(cov_fmri_rel), 6))


if __name__ == "__main__":
    main()